### ISSUE TITLE
Button to use extension now showing up

### ISSUE THREAD

**Issue by Orangy-Man** [Patrick-orz/PopupLyrics-Plus#8]
**Are you using the LATEST version?**
im using V2.2.1

**Describe the Bug**
i put the extention in my folder and ran both commands but it will not show up in spotify

**To Reproduce**
follow installation process

**Expected Behavior**
an option for popuplyricsplys to show up

**PopupLyricsPlus Settings**
none

**Screenshots or Video**
![image](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/169196927/913e8e2a-44ab-4072-b252-45358197180f)

**Additional context**
i tried using this extention a long time ago and i couldnt even get the lyrics to scroll unless i was focused on spotify

**Comment by Orangy-Man** [comment]
if i did something wrong please tell me

**Comment by Patrick-orz** [comment]
Thank you for the report~

I could not reproduce the issue on latest spotify, spicetify, and PopupLyricsPlus versions.

Can you make sure that you have placed the extension js file in the correct spicetify directory, and added "popupLyricsPlus.js" as an extension in your config?
**Post your _config-xpui.ini_ here as well so I can investigate further.** _config-xpui.ini_ should be found in the source spicetify directory, along with other directories such as _BackUp_, _CustomApps_, and _Extensions_.

PS: In terms of the "lyrics not scrolling when not focused on spotify" mentioned in the additional context, that should have been resolved in the latest version.

**Comment by Orangy-Man** [comment]
it started to work today like 10 minutes ago. im not sure if i did anything or if you did anything but the issue seems to be resolved for now

**Comment by Orangy-Man** [comment]
and for the scrolling issue, its still happening. i dont know how to fix that

**Comment by Patrick-orz** [comment]
I'm glad at least the button shows up now. 

In terms of the scrolling issue, it has been known to be somewhat unstable. The fact that you are on windows (I believe) might contribute to it as well, as most testing and development is done on mac.

I have an interesting solution that might get the scrolling to function. Try enabling **both** the original PopupLyrics plugin and PopupLyricsPlus. See if original PopupLyrics scroll fine, then try PopupLyricsPlus. I find PopupLyricsPlus to scroll correctly somehow after a few resets and boots with PopupLyrics. I know this is a bizarre solution but it's worth a try.

Anyhow, this issue is focused on the extension's button, which ended up being resolved (so I would close it). If you still want support on the scrolling, start a new issue and I would be happy to help you there!
